# Generated by Django 3.0 on 2024-08-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20240820_1744'),
        ('oc_lettings_site', '0002_auto_20240820_1119'),
    ]

    operations = [
    ]
