name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          coverage run manage.py test
          coverage report -m
          coverage html
        continue-on-error: false

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oc_lettings_site:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oc_lettings_site:${{ github.sha }}

      - name: List all files (debugging)
        run: ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Render deployment
        run: |
          curl -X POST -H "Accept: application/json" -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "YOUR_SERVICE_ID"}' \
          https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys