name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
# test job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          coverage run manage.py test
          coverage report -m
          coverage html
        continue-on-error: false

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/oc_lettings_site

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image with commit hash and 'latest' tag
        run: |
          # Build et push l'image avec le commit hash tag
          docker buildx build --push --tag $DOCKER_IMAGE:${{ github.sha }} .

          # Tag et push la même image avec le tag 'latest' tag
          docker buildx build --push --tag $DOCKER_IMAGE:latest .

      - name: List Docker images
        run: docker images

      - name: Display Docker image variable
        run: echo $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/oc_lettings_site:latest
      RENDER_SERVICE_ID: YOUR_SERVICE_ID
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    steps:
      - name: Deploy to Render
        run: |
          # Test url de l'image docker hub push lors du build sur dockerhub
          IMAGE_URL="${{ env.DOCKER_IMAGE }}"
          curl -X POST "https://api.render.com/v1/services/${{ env.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d "{\"image\":\"$IMAGE_URL\", \"clearCache\":false}"
