name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          coverage run manage.py test
          coverage report -m
          coverage html
        continue-on-error: false

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/oc_lettings_site

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Dockerfile
        run: |
          echo 'FROM python:3.11' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY . /app' >> Dockerfile
          echo 'RUN pip install --no-cache-dir -r requirements.txt' >> Dockerfile
          echo 'EXPOSE 8000' >> Dockerfile
          echo 'CMD ["gunicorn", "myapp.wsgi:application", "--bind", "0.0.0.0:8000"]' >> Dockerfile

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --push --tag $DOCKER_IMAGE:${{ github.sha }} .

      - name: List Docker images
        run: docker images

      - name: Display Docker image variable
        run: echo $DOCKER_IMAGE

      - name: Verify Docker build
        run: |
          docker images | grep $DOCKER_IMAGE
